// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaamybhhcftortusmbzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYW15YmhoY2Z0b3J0dXNtYnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjE3MTUsImV4cCI6MjA2NTc5NzcxNX0.Fcxk7bExVlnXttzIUchNiJzDLqokGtMEaDRluGBH4fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);